version: '3.8'
services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: test
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - '8080:8080'
